version: 2

sources:
  - name: bike_sales
    database: bike_shop_dq_db
    schema: sales
    tables:
      - name: customers_dq
      - name: orders_dq
      - name: order_items_dq
      - name: staffs_dq
      - name: stores_dq
  - name: bike_production
    database: bike_shop_dq_db
    schema: production
    tables:
      - name: brands_dq
      - name: categories_dq
      - name: products_dq
      - name: stocks_dq
